name: Update Readme

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-wakatime:
    name: Update stats
    runs-on: ubuntu-latest
    steps:
      - name: Update with wakatime
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: daanbreur
          SHOW_TITLE: false
  update-youtube:
    needs: update-wakatime
    name: Update Latest YouTube Videos
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Update Youtube List
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBE"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCGWs9foruVqIoEf2sLBfJAg"
          commit_message: "Updated youtube videos"
          committer_username: "ReadmeBot"
          committer_email: "bots@daanbreur.systems"
          gh_token: ${{ secrets.GH_TOKEN }}
  update-blogpost:
      needs: [update-wakatime, update-youtube]
      name: Update Latest Blog Post
      runs-on: ubuntu-latest
      steps:
        - name: Clone repository
          uses: actions/checkout@v2
        - name: Update Blogpost List
          uses: gautamkrishnar/blog-post-workflow@master
          with:
            comment_tag_name: "BLOG"
            feed_list: "https://dev.to/feed/daanbreur, https://github.daanbreur.systems/feed.xml"
            commit_message: "Updated blogposts"
            committer_username: "ReadmeBot"
            committer_email: "bots@daanbreur.systems"
            gh_token: ${{ secrets.GH_TOKEN }}
  update-writeup:
      needs: [update-wakatime, update-youtube, update-blogpost]
      name: Update Writeup List
      runs-on: ubuntu-latest
      steps:
        - name: Clone repository
          uses: actions/checkout@v2
        - name: Update Writeup List
          uses: gautamkrishnar/blog-post-workflow@master
          with:
            comment_tag_name: "WRITEUP"
            feed_list: "https://blog.daanbreur.systems/feed.xml"
            commit_message: "Updated writeups"
            committer_username: "ReadmeBot"
            committer_email: "bots@daanbreur.systems"
            gh_token: ${{ secrets.GH_TOKEN }}
