name: Update Readme

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update-wakatime:
    name: Update stats
    runs-on: ubuntu-latest
    steps:
      - name: Update with wakatime
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TITLE: false
  update-writeup:
      needs: update-wakatime
      name: Update Writeup List
      runs-on: ubuntu-latest
      steps:
        - name: Clone repository
          uses: actions/checkout@v2
        - name: Update Writeup List
          uses: gautamkrishnar/blog-post-workflow@master
          with:
            comment_tag_name: "WRITEUP"
            feed_list: "https://blog.daanbreur.systems/post/index.xml,https://blog.duckz.org/post/index.xml"
            commit_message: "Updated writeups"
            committer_username: "Cute little readme bot"
            committer_email: "git@daanbreur.systems"
            gh_token: ${{ secrets.GH_TOKEN }}
